// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateTicker(ctx context.Context, arg CreateTickerParams) (Ticker, error)
	DeleteTicker(ctx context.Context, id int64) error
	GetTicker(ctx context.Context, id int64) (Ticker, error)
	ListTickers(ctx context.Context, arg ListTickersParams) ([]Ticker, error)
	UpdateDescriptionTicker(ctx context.Context, arg UpdateDescriptionTickerParams) (Ticker, error)
}

var _ Querier = (*Queries)(nil)
