// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: rpc_create_ticker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTickerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol      string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Exchange    string `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Currency    string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *CreateTickerRequest) Reset() {
	*x = CreateTickerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_ticker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTickerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTickerRequest) ProtoMessage() {}

func (x *CreateTickerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_ticker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTickerRequest.ProtoReflect.Descriptor instead.
func (*CreateTickerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_ticker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTickerRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateTickerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTickerRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *CreateTickerRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateTickerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker *Ticker `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
}

func (x *CreateTickerResponse) Reset() {
	*x = CreateTickerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_ticker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTickerResponse) ProtoMessage() {}

func (x *CreateTickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_ticker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTickerResponse.ProtoReflect.Descriptor instead.
func (*CreateTickerResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_ticker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTickerResponse) GetTicker() *Ticker {
	if x != nil {
		return x.Ticker
	}
	return nil
}

var File_rpc_create_ticker_proto protoreflect.FileDescriptor

var file_rpc_create_ticker_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x3a, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x42, 0x13, 0x5a, 0x11, 0x72, 0x70, 0x63, 0x2d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_ticker_proto_rawDescOnce sync.Once
	file_rpc_create_ticker_proto_rawDescData = file_rpc_create_ticker_proto_rawDesc
)

func file_rpc_create_ticker_proto_rawDescGZIP() []byte {
	file_rpc_create_ticker_proto_rawDescOnce.Do(func() {
		file_rpc_create_ticker_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_ticker_proto_rawDescData)
	})
	return file_rpc_create_ticker_proto_rawDescData
}

var file_rpc_create_ticker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_ticker_proto_goTypes = []any{
	(*CreateTickerRequest)(nil),  // 0: pb.CreateTickerRequest
	(*CreateTickerResponse)(nil), // 1: pb.CreateTickerResponse
	(*Ticker)(nil),               // 2: pb.Ticker
}
var file_rpc_create_ticker_proto_depIdxs = []int32{
	2, // 0: pb.CreateTickerResponse.ticker:type_name -> pb.Ticker
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_ticker_proto_init() }
func file_rpc_create_ticker_proto_init() {
	if File_rpc_create_ticker_proto != nil {
		return
	}
	file_ticker_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_ticker_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateTickerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_ticker_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateTickerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_ticker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_ticker_proto_goTypes,
		DependencyIndexes: file_rpc_create_ticker_proto_depIdxs,
		MessageInfos:      file_rpc_create_ticker_proto_msgTypes,
	}.Build()
	File_rpc_create_ticker_proto = out.File
	file_rpc_create_ticker_proto_rawDesc = nil
	file_rpc_create_ticker_proto_goTypes = nil
	file_rpc_create_ticker_proto_depIdxs = nil
}
