// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: service_ticker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TickerServicer_CreateTicker_FullMethodName = "/pb.TickerServicer/CreateTicker"
)

// TickerServicerClient is the client API for TickerServicer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerServicerClient interface {
	CreateTicker(ctx context.Context, in *CreateTickerRequest, opts ...grpc.CallOption) (*CreateTickerResponse, error)
}

type tickerServicerClient struct {
	cc grpc.ClientConnInterface
}

func NewTickerServicerClient(cc grpc.ClientConnInterface) TickerServicerClient {
	return &tickerServicerClient{cc}
}

func (c *tickerServicerClient) CreateTicker(ctx context.Context, in *CreateTickerRequest, opts ...grpc.CallOption) (*CreateTickerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTickerResponse)
	err := c.cc.Invoke(ctx, TickerServicer_CreateTicker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerServicerServer is the server API for TickerServicer service.
// All implementations must embed UnimplementedTickerServicerServer
// for forward compatibility.
type TickerServicerServer interface {
	CreateTicker(context.Context, *CreateTickerRequest) (*CreateTickerResponse, error)
	mustEmbedUnimplementedTickerServicerServer()
}

// UnimplementedTickerServicerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTickerServicerServer struct{}

func (UnimplementedTickerServicerServer) CreateTicker(context.Context, *CreateTickerRequest) (*CreateTickerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTicker not implemented")
}
func (UnimplementedTickerServicerServer) mustEmbedUnimplementedTickerServicerServer() {}
func (UnimplementedTickerServicerServer) testEmbeddedByValue()                        {}

// UnsafeTickerServicerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerServicerServer will
// result in compilation errors.
type UnsafeTickerServicerServer interface {
	mustEmbedUnimplementedTickerServicerServer()
}

func RegisterTickerServicerServer(s grpc.ServiceRegistrar, srv TickerServicerServer) {
	// If the following call pancis, it indicates UnimplementedTickerServicerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TickerServicer_ServiceDesc, srv)
}

func _TickerServicer_CreateTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerServicerServer).CreateTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TickerServicer_CreateTicker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerServicerServer).CreateTicker(ctx, req.(*CreateTickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickerServicer_ServiceDesc is the grpc.ServiceDesc for TickerServicer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerServicer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TickerServicer",
	HandlerType: (*TickerServicerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTicker",
			Handler:    _TickerServicer_CreateTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_ticker.proto",
}
